---
name: "Inject token for current repo/domain cache"
description: "Uses the provided token to load into the credential cache manager of git to use it globally. After execution the cache will be cleared."
author: "BlackDark"
branding:
  icon: "log-in"
  color: "blue"
inputs:
  token:
    description: "Token for authentication. As default use secrets.GITHUB_TOKEN"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/cleanup/index.js"
