---
name: "Copy git authorization to global"
description: "Copies the temporary token to global git config"
author: "BlackDark"
branding:
  icon: "log-in"
  color: "blue"
inputs:
  token:
    description: "Token to be used as x-access-token auth. As default use secrets.GITHUB_TOKEN "
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
  post: "dist/cleanup/index.js"
